require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  UseCache: true
  NewCops: enable
Layout/LineLength:
  Exclude:
    # example hash lines known to be long and need restructuring eventually
    - spec/helpers.rb

# Layout preferences
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

# I am careful to not leak state between tests
# Eventually this can be cleaned up but it is not a priority
RSpec/InstanceVariable:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false

# Temporarily disabled
Style/Documentation:
  # document classes after structure/design is more set
  Enabled: false

