inherit_gem:
  almost_standard: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'utils/test_timetwister.rb'

Naming/MethodParameterName:
  AllowedNames: n, n1, n2, yr, x
# Style/NumericLiterals:
#   Enabled: false

# # I am careful to not leak state between tests
# # Eventually this can be cleaned up but it is not a priority
# RSpec/InstanceVariable:
#   Enabled: false
# RSpec/BeforeAfterAll:
#   Enabled: false
# # Nested groups help create documentation from tests
# RSpec/NestedGroups:
#   Enabled: false
