require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  UseCache: true
  NewCops: enable
Layout/LineLength:
  Exclude:
    - spec/helpers.rb
RSpec/InstanceVariable:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
