require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  UseCache: true
  NewCops: enable

# Layout preferences
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

# I am careful to not leak state between tests
# Eventually this can be cleaned up but it is not a priority
RSpec/InstanceVariable:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
# Nested groups help create documentation from tests
RSpec/NestedGroups:
  Enabled: false
  
# Temporarily disabled
Style/Documentation:
  # document classes after structure/design is more set
  Enabled: false

