= Development notes

Notes on things still to be implemented, things to fix, etc.


== To-do
=== option for handling output of EDTF when only year or year/month are known

==== one configurable option for month level
Example: 2004

If option is `none` (default), output `2004`

If option is `unspecified_digits`, output `2004-XX`

If option is a number (say 4), output `2004-04`

==== one configurable option for day level
Example: April 2004

If option is `none` (default), output `2004-04`

If option is `unspecified_digits`, output `2004-04-XX`

If option is a number (say 7), output `2004-04-07`

==== interactions

If month is none, only none is valid for day. Any other value for day will be ignored.

Otherwise, you can set them independently:

Example: 2004

month: unspecified_digits, day: 17 = 2004-XX-17

month: 10, day: unspecified_digits = 2004-10-XX

== Notes

Islandora has no built-in date functionality. It uses the pre-parsed values in MODS (I7) or Drupal fields (I8), so we can basically do whatever with the date parsing.

=== ISO8601 and BCE

From https://en.wikipedia.org/wiki/ISO_8601#Years

ISO 8601 prescribes, as a minimum, a four-digit year [YYYY] to avoid the year 2000 problem. It therefore represents years from 0000 to 9999, year 0000 being equal to 1 BC and all others AD. However, years prior to 1583 are not automatically allowed by the standard. Instead "values in the range [0000] through [1582] shall only be used by mutual agreement of the partners in information interchange."

From ISO 8601-2:2019(E) 4.4.1.2 (p. 10):

____
`-1985` in implicit form expresses the calendar year -1985.

...

When a negative calendar year represents a date, the negative value is to represent the number of years prior to the year zero (0) (year zero is expressed as `0000` in implicit form

...

The year immediately preceding year zero (0) is expressed as `-0001` in implicit form
____

From https://solr.apache.org/guide/8_10/working-with-dates.html: 

____
There must be a leading '-' for dates prior to year 0000, and Solr will format dates with a leading '+' for years after 9999. Year 0000 is considered year 1 BC; there is no such thing as year 0 AD or BC.

...

-0009 – The year 10 BC. A 0 in the year position is 0 AD, and is also considered 1 BC.
____

=== Early/mid/late season

to do

=== Early/mid/late month

to do

=== Early/mid/late decade

Examples: Early 1990s, mid-1990s, late 1990s

There is no standard agreement anywhere about what years of the decade constitute early, mid, and late. Preferences for breaking this up include: 3-4-3 and 4-2-4.

CollectionSpace's date parser handles this as follows:

early 1990s = 1990-1993

mid 1990s = 1994-1996

late 1990s = 1997-1999


This is different than what TimeTwister returns:

early 1990s = 1990-1995

mid 1990s = 1993-1998

late 1990s = 1995-1999

For a cohesive user experience between migration/batch import and use of CollectionSpace UI, we need to do what CS does.

=== Early/mid/late year

Examples: Early 2020, mid-2020, late 2020

In Islandora we'll have to feed it pre-parsed values in MODS or Drupal fields.

CollectionSpace parses these as follows, so we will go with that as the requirement:

early 2020 = 2020-01-01 to 2020-04-30
mid 2020 = 2020-05-01 to 2020-08-31
late 2020 = 2020-09-01 to 2020-12-31

=== Seasons (textual)
Go with what CS does.

*Winter 2020*

CS = 2020-01-01 - 2020-03-31

TT = 2020-01-01 - 2020-03-20

*Spring 2020*

CS = 2020-04-01 - 2020-06-30

Timetwister = 2020-03-20 - 2002-06-21

*Summer 2020*

CS = 2020-07-01 - 2020-09-30

TT = 2020-06-21 - 2020-09-23

*Fall 2020*

CS = 2020-10-01 - 2020-12-31

TT = 2020-09-23 - 2020-12-22


=== Before/after dates

Example: before 1750

Since CollectionSpace is museum oriented, it's possible we need to support *really* old dates.

Cspace only parses a date like this into the latest date. Earliest/single date is nil. So, initially we will just return a single date value (not an inclusive range) (i.e. 1750-01-01), with "before" certainty value.

Example: after 1750

Since the latest date is TODAY, we have an end point and can return the inclusive range. Certainty "after" is assigned to the given date. Certainty "before" is assigned to the current date.

=== Centuries

example: 19th century

CS = 1801-01-01 - 1900-12-31

TT = 1800-01-01 - 1899-12-31

Because of the difference in years used in setting ranges, I'm going to go with CS and not compare what early/mid/late values are set.

`early/mid/late 18th century`

named, early = 1701-01-01 - 1734-12-31

named, mid = 1734-01-01 - 1767-12-31

named, late = 1767-01-01 - 1800-12-31

`early/mid/late 1900s or 19XX`

other, early = 1900-01-01 - 1933-12-31

other, mid = 1933-01-01 - 1966-12-31

other, late = 1966-01-01 - 1999-12-31

=== Unspecified digits

.Note from ISO 8601-2:2019(E) 9.2.1.2.d (p. 38)
____
The expression '1985-XX-XX' refers to a day in the year 1985 and differs in meaning from the expression '1985', which refers to the year 1985. Similarly, '1985-04' is an expression with reduced precision, while '1985-04-XX' is an expression of the complete representation.
____

This means that `1985-XX-XX` is basically a shorthand for `[1985-01-01..1985-12-31]`, which means "one of the days in the set of days in the year 1985".

=== Throwing out the technical definition of "time interval" (ISO 8601) or "inclusive range" (as per Timetwister)

Timetwister simply says:

____
`:inclusive_range` is whether or not the input value is a range
____

My guess from testing various values was that, if `date_end` > `date_start`, Timetwister considers it to be an `:inclusive_range`. However, the code isn't clear about this.

.Note from ISO 8601-2:2019(E) 8.4.2.d (p. 33)
____
A decade expresses decade precision, "approximate decade" means that "the decade is approximated to be the 1980s, but it might be (for example) the 1970s or 1990s." It does not mean the time interval beginning approximately at the beginning of and ending approximately at the end of the 1980s. The latter would be expressed as `1980~/1990~` and would hae year precision.
____

According to the ISO 8601-2:2019(E) note on unspecified digits above, `1985-XX-XX` is technically not an inclusive date range, but `1985` is, because the latter refers to the whole year.

In the GLAM domain, however, we do not tend to think of a publication date of `1985` as indicating a range.

When we record a creation date of `1990s`, we are not necessarily explicitly saying that the object was being created for the entire decade. This is generally a shorthand for "sometime in the 1990s, without specifying any level of granularity".

When we say an electric lamp was made `before 1950`, we do not literally mean that it was made at some point from the beginning of time until the end of 1949. 

Also, our main purpose/concern is not ontological truthiness, but to support search and discovery in information systems, which often means dealing with Solr, which has a https://solr.apache.org/guide/8_10/working-with-dates.html#date-range-formatting[DateRangeField field type] that actually treats `2001-01-01` as a range since under the hood there's also a timestamp added.

So, if we are not recording date/times down to a millisecond, everything is a range.

I'm deciding to remove specification of "inclusive range" from the `Emendate::Result`. Instead, it should be concerned with returning:

* explicit/known (given level of granularity) date start/end
* inferred YYYY-MM-DD full date start/end
* a single value per result, which can be used as a sort date

