= Emendate options

== ambiguous_month_day

What is this?:: 2/3 could mean February 3 or March 2
Default value:: `:as_month_day`, resulting in February 3
Alternate value:: `:as_day_month`, resulting in March 2

Does not apply when there is no ambiguity. For example, 29/2 will always be interpreted as February 29, as there is no month 29.

== ambiguous_month_year

What is this?:: Does 2010-12 mean 2010-2012, or December 2010?
Default value:: `:as_year`, resulting in 2010-2012
Alternate value:: `as_month`, resulting in December 2010

[NOTE]
====
This also applies to ambiguity between year and numerically expressed season, such as 2020-21, which could mean 2020-2021 or Spring 2020.
====

Does not apply when there is no ambiguity. For example, 2020-10 will always be interpreted as October 2020, since a range of 2020-2010 would be nonsense.

== ambiguous_year_rollback_threshold

What is this?:: If a two-digit year is to be coerced to four digits, what should the first two digits be? Is '20' 1920 or 2020?
Default value:: the current year's last two digits. So, in 2021, it is `21`
Alternate value:: any 2 digit number


Numbers less than this 2-digit value are treated as current century.

Numbers greater than or equal to this are treated as the previous century.

If we are using the default and the current year is 2021...

- a value of `21` will become `1921`
- a value of `20` will become `2020`

[TIP]
====
This option is irrelevant if you are using `two_digit_year_handling: :literal`
====

== pluralized_date_interpretation

What is this?:: Should 1900s be interpreted as 1900-1909, or 1900-1999? Should 2000s be interpreted as 2000-2009, or 2000-2999?
Default value:: `:decade`, resulting in `1900-1909` and `2000-2009`, respectively
Alternate value:: `:broad`, resulting in `1900-1999` and `2000-2999`, respectively

1990s will always be interpreted as 1990-1999.

== square_bracket_interpretation

What is this?:: Should square brackets around a date string be interpreted as an inferred date, or as an EDTF "one of" set?
Default value:: `:inferred_date`
Alternate value:: `:edtf_set`

== two_digit_year_handling

What is this?::  Should 80 be treated as 1980 or literally as the year 80?
Default value:: `:coerce`, resulting in 1980
Alternate value:: `:literal`, resulting in 80

When using the default, also pay attention to the `ambiguous_year_rollback_threshold` option.
