:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Using Emendate

The following examples assume you cloned the repo into a folder called `emendate` and have done:

----
cd emendate
bin/console
----

toc::[]

== Basic use

The main command is:

`Emendate.parse('early 19th c.')`

This is also the way to use Emendate in other applications.

The parsed result is:

The parsed result is an `Emendate::Result` Ruby object:

[source]
----
#<Emendate::Result:0x00007fbbdcbd5bd8
 @dates=
  [#<Emendate::ParsedDate:0x00007fbbdcbd5e58
    @certainty=[],
    @date_end=nil,
    @date_end_full="1834-12-31",
    @date_start=nil,
    @date_start_full="1801-01-01",
    @inclusive_range=true,
    @index_dates=[],
    @original_string=nil>],
 @errors=[],
 @original_string="early 19th c.",
 @warnings=[]>
----

You may pass in the following to return a Ruby Hash:

[source]
----
Emendate.parse('mid 1990s').to_h
=> {:original_string=>"mid 1990s",
 :dates=>
  [{:original_string=>nil,
    :index_dates=>[],
    :date_start=>nil,
    :date_end=>nil,
    :date_start_full=>"1994-01-01",
    :date_end_full=>"1996-12-31",
    :inclusive_range=>true,
    :certainty=>[]}],
 :errors=>[],
 :warnings=>["Interpreting pluralized year as decade"]}
----

Or, the following to return JSON:

[source]
----
Emendate.parse('mid 1990s').to_json
=> "{\"original_string\":\"mid 1990s\",\"dates\":[{\"original_string\":null,\"index_dates\":[],\"date_start\":null,\"date_end\":null,\"date_start_full\":\"1994-01-01\",\"date_end_full\":\"1996-12-31\",\"inclusive_range\":true,\"certainty\":[]}],\"errors\":[],\"warnings\":[\"Interpreting pluralized year as decade\"]}"
----

For more details on the returned result, see https://github.com/kspurgin/emendate/blob/main/docs/output.adoc[docs/output.adoc].

== Passing in options

See https://github.com/kspurgin/emendate/blob/main/docs/options.adoc[Emendate options] for details on the available options and what they do. The following is just to illustrate the use of options and their effect. 

.Using default settings
[source]
----
Emendate.parse('2005-06')
=> #<Emendate::Result:0x00007fdfb41aa2c0
 @dates=
  [#<Emendate::ParsedDate:0x00007fdfb41aa428
    @certainty=[],
    @date_end=nil,
    @date_end_full="2006-12-31",
    @date_start=nil,
    @date_start_full="2005-01-01",
    @inclusive_range=true,
    @index_dates=[],
    @original_string=nil>],
 @errors=[],
 @original_string="2005-06",
 @warnings=["Ambiguous year + month/season/year treated as_year"]>
----

.Using an alternative option
[source]
----
Emendate.parse('2005-06', ambiguous_month_year: :as_month)
=> #<Emendate::Result:0x00007fdfd4b6d350
 @dates=
  [#<Emendate::ParsedDate:0x00007fdfd4b6d490
    @certainty=[],
    @date_end=nil,
    @date_end_full="2005-06-30",
    @date_start=nil,
    @date_start_full="2005-06-01",
    @inclusive_range=nil,
    @index_dates=[],
    @original_string=nil>],
 @errors=[],
 @original_string="2005-06",
 @warnings=["Ambiguous year + month/season/year treated as_month"]>
----

.Default result for value where multiple options could have an effect
[source]
----
Emendate.parse('mid 1800s to 2/23/21')
=> #<Emendate::Result:0x00007fdfb40bbdc8
 @dates=
  [#<Emendate::ParsedDate:0x00007fdfb40c0710
    @certainty=[],
    @date_end=nil,
    @date_end_full="1921-02-23",
    @date_start=nil,
    @date_start_full="1804-01-01",
    @inclusive_range=true,
    @index_dates=[],
    @original_string=nil>],
 @errors=[],
 @original_string="mid 1800s to 2/23/21",
 @warnings=["Interpreting pluralized year as decade"]>
----

.Setting multiple options at once
[source]
----
Emendate.parse('mid 1800s to 2/23/21', ambiguous_year_rollback_threshold: 0, pluralized_date_interpretation: :broad)
=> #<Emendate::Result:0x00007fdfb4142580
 @dates=
  [#<Emendate::ParsedDate:0x00007fdfb4142760
    @certainty=[],
    @date_end=nil,
    @date_end_full="1921-02-23",
    @date_start=nil,
    @date_start_full="1833-01-01",
    @inclusive_range=true,
    @index_dates=[],
    @original_string=nil>],
 @errors=[],
 @original_string="mid 1800s to 2/23/21",
 @warnings=["Interpreting pluralized year as century"]>
----

== Utility script for getting Emendate output for a batch in CSV format

Exit out of the console if you are in it.

`cd` into `emendate/utils`.

Run the following command:

`ruby batch_result_report.rb -i /path_to/your_date_data.csv`

A file called `your_date_data_report.csv` will be written to the same directory in which your input file is located.

This script assumes:

- the date values are in the first column of the input CSV (it does not look past the first column and does not return subsequent columns in the report)
- there are no headers (if there is a header, it'll just try to parse it as a date, which will show up with an Emendate error in the report, but you can just ignore that row)

== Working with `ProcessingManager` for development/debugging

The `Emendate.process` command returns a the ProcessingManager object, which represents the date at every stage of transformation, including the final result. It is big and difficult to visually parse all at once, so assign it to a variable when you call it:

`pm = Emendate.process('Early 19th c.')`

To see what specific parts of it you can request:

`pm.instance_variables`

This returns a list of things you can put after `pm.` (remove the `:@`). For example, the normalized version of your original input string:

`pm.norm_string`

You can ignore `:@aasm`, which is internally used for processing.

`:@errors` and `:@warnings` will show any messages in those categories. Errors are problems/issues that can't currently be handled by Emendate. Errors may indicate further development needed, or just unexpected input that Emendate won't really ever gracefully deal with.

Warnings are things Emendate handled, but which you might want to review because the input was in some way ambiguous or odd.

The rest contain a representation of the original string at each stage of processing. `:@tokens` always shows the latest stage in processing. For more details on the processing stages and what the data will look like at each stage, see https://github.com/kspurgin/emendate/blob/main/docs/processing.adoc[How Emendate processes date strings].


This is not in the list of instance_variables you can call, but will show you if processing finished successfully (`done`) or not (`failed`):

`pm.state`


== Working with the test set
See separate page in this same directory.
