:toc:
:toc-placement!:

= Using Emendate

The following examples assume you cloned the repo into a folder called `emendate` and have done:

----
cd emendate
bin/console
----

toc::[]

== Basic use

The main command is:

`Emendate.parse('early 19th c.')`

This is also the way to use Emendate in other applications.

The parsed result is:

----
{:original_string=>"early 19th c.",
 :errors=>[],
 :warnings=>[],
 :result=>
  [{:index_dates=>nil,
    :date_start=>nil,
    :date_end=>nil,
    :date_start_full=>"1801-01-01",
    :date_end_full=>"1834-12-31",
    :inclusive_range=>true,
    :certainty=>[]}]}
----

For more details on the returned result, see https://github.com/kspurgin/emendate/blob/main/docs/output.adoc[docs/output.adoc].

== Passing in options

See https://github.com/kspurgin/emendate/blob/main/docs/options.adoc[Emendate options] for details on the available options and what they do. The following is just to illustrate the use of options and their effect. 

.Using default settings
----
Emendate.parse('2005-06')
=> {:original_string=>"2005-06",
 :errors=>[],
 :warnings=>["Ambiguous year + month/season/year treated as_year"],
 :result=>
  [{:index_dates=>nil,
    :date_start=>nil,
    :date_end=>nil,
    :date_start_full=>"2005-01-01",
    :date_end_full=>"2006-12-31",
    :inclusive_range=>true,
    :certainty=>[]}]}
----

.Using an alternative option
----
Emendate.parse('2005-06', ambiguous_month_year: :as_month)
=> {:original_string=>"2005-06",
 :errors=>[],
 :warnings=>["Ambiguous year + month/season/year treated as_month"],
 :result=>
  [{:index_dates=>nil,
    :date_start=>nil,
    :date_end=>nil,
    :date_start_full=>"2005-06-01",
    :date_end_full=>"2005-06-30",
    :inclusive_range=>nil,
    :certainty=>[]}]}
----

.Default result for value where multiple options could have an effect
----
Emendate.parse('mid 1900s to 2/23/21')
=> {:original_string=>"mid 1900s to 2/23/21",
 :errors=>[],
 :warnings=>[],
 :result=>
  [{:index_dates=>nil,
    :date_start=>nil,
    :date_end=>nil,
    :date_start_full=>"1904-01-01",
    :date_end_full=>"1921-02-23",
    :inclusive_range=>true,
    :certainty=>[]}]}
----

.Setting multiple options at once
----
Emendate.parse('mid 1900s to 2/23/21', ambiguous_year_rollback_threshold: 0, pluralized_date_interpretation: :broad)
=> {:original_string=>"mid 1900s to 2/23/21",
 :errors=>[],
 :warnings=>[],
 :result=>
  [{:index_dates=>nil,
    :date_start=>nil,
    :date_end=>nil,
    :date_start_full=>"1933-01-01",
    :date_end_full=>"1921-02-23",
    :inclusive_range=>true,
    :certainty=>[]}]}
----

== Utility script for getting Emendate output for a batch in CSV format

Exit out of the console if you are in it.

`cd` into `emendate/utils`.

Run the following command:

`ruby batch_result_report.rb -i /path_to/your_date_data.csv`

A file called `your_date_data_report.csv` will be written to the same directory in which your input file is located.

This script assumes:

- the date values are in the first column of the input CSV (it does not look past the first column and does not return subsequent columns in the report)
- there are no headers (if there is a header, it'll just try to parse it as a date, which will show up with an Emendate error in the report, but you can just ignore that row)

== Working with `ProcessingManager` for development/debugging

The `Emendate.process` command returns a the ProcessingManager object, which represents the date at every stage of transformation, including the final result. It is big and difficult to visually parse all at once, so assign it to a variable when you call it:

`pm = Emendate.process('Early 19th c.')`

To see what specific parts of it you can request:

`pm.instance_variables`

This returns a list of things you can put after `pm.` (remove the `:@`). For example, the normalized version of your original input string:

`pm.norm_string`

You can ignore `:@aasm`, which is internally used for processing.

`:@errors` and `:@warnings` will show any messages in those categories. Errors are problems/issues that can't currently be handled by Emendate. Errors may indicate further development needed, or just unexpected input that Emendate won't really ever gracefully deal with.

Warnings are things Emendate handled, but which you might want to review because the input was in some way ambiguous or odd.

The rest contain a representation of the original string at each stage of processing. `:@tokens` always shows the latest stage in processing. For more details on the processing stages and what the data will look like at each stage, see https://github.com/kspurgin/emendate/blob/main/docs/processing.adoc[How Emendate processes date strings].


This is not in the list of instance_variables you can call, but will show you if processing finished successfully (`done`) or not (`failed`):

`pm.state`


== Working with the test set

To see a list of all the date string values in the test set:

`Emendate::EXAMPLES.keys`

To see the list of all strings in the test set, with the tags assigned to each:

`Emendate.example_tags`

[NOTE]
====
The following will make more sense if you have read https://github.com/kspurgin/emendate/blob/main/docs/processing.adoc[How Emendate processes date strings].
====

This will output all unique type patterns being generated from the example strings:

`Emendate.unique_type_patterns`

Beneath each type pattern is a list of the original strings that have ended up with this pattern.

Running the command as shown above shows you all segment types, for all strings, and shows you the final result of the `SegmentSet` processing, with default configuration.

Of course, there are other options!

To see only the ``Segment``s that are/can be parts of actual dates, from just after date part tagging, only for examples with the inferred tag:

`Emendate.unique_type_patterns(type: :date, stage: :segment_dates, tag: :inferred, options: {ambiguous_month_day: :as_day_month})`

Note that the options need to be wrapped in curly braces here.

Also note that `stage` indicates the processing step that your desired input feeds into. Processing moves from `tag_date_parts` to `segment_dates`, so if you want see the results of date part tagging, the stage the data is ready for is `segment_dates`. 
